{
 "title": "Airflow cluster dashboard",
 "description": "Dashboard for Airflow ",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(airflow_dagbag_size, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduler heartbeat",
   "type": "timeseries",
   "description": "‫این کوئری بررسی می‌کند که آیا در ۵ دقیقه گذشته heartbeat ارسال شده یا نه. اگر عددش0 بود یعنی Scheduler مشکلی دارد.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat{namespace=\"$namespace\"}[5m])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Triggerer heartbeat",
   "type": "timeseries",
   "description": "‫این نرخ heartbeat را در ۵ دقیقه گذشته می‌دهد. مقدار 0 یعنی triggerer گیر کرده یا کرش کرده است.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(airflow_triggerer_heartbeat{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "timeseries",
   "description": "‫airflow_dagrun_duration یک متریک histogram (یا summary) است که مدت زمان اجرای یک DAG Run را از لحظه‌ای که شروع می‌شود تا لحظه‌ای که به پایان می‌رسد، اندازه می‌گیرد.\n\n‫هر بار که یک DAG Run به حالت success, failed, skipped, یا upstream_failed می‌رسد، این متریک به‌روزرسانی می‌شود.\n\n‫وقتی یک DAG اجرا می‌شود (چه به صورت زمان‌بندی‌شده، دستی یا با ترایگر خارجی)،‫ یک DAG Run ساخته می‌شود که نمایانگر اجرای کل DAG در آن لحظه است.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration{namespace=\"$namespace\"}",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Success DAG run duration",
   "type": "timeseries",
   "description": "‫این متریک در واقع مدت‌زمان اجرای DAGهایی را نشان می‌دهد که با موفقیت (state = success) به پایان رسیده‌اند.\n\n‫این متریک مدت زمان (Duration) بین start_date و end_date یک DAG Run موفق را اندازه‌گیری می‌کند. فقط برای DAGهایی که با موفقیت کامل شده‌اند (نه failed یا skipped یا ...).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success{namespace=\"$namespace\"}",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run schedule delay",
   "type": "timeseries",
   "description": "‫میزان تاخیر (Delay) بین زمان برنامه‌ریزی‌شده (Scheduled Time) و زمان واقعی شروع اجرای یک DAG Run را اندازه می‌گیرد.\n\n‫وقتی یک DAG قرار است در زمان مشخصی اجرا شود (مثلاً هر روز ساعت 1 صبح)، این متریک نشان می‌دهد که واقعاً چند میلی‌ثانیه یا ثانیه بعد از آن زمان برنامه‌ریزی‌شده اجرا شده است.\n\n‫اگر این مقدار زیاد باشد یعنی اجرای DAG با تأخیر شروع شده (مثلاً به خاطر بار زیاد Scheduler یا مشکلات منابع).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_dagrun_schedule_delay{namespace=\"$namespace\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Number of running tasks on executor",
   "type": "timeseries",
   "description": "‫این متریک نشان‌دهنده‌ی تعداد تسک‌های (Task) در حال اجرای فعلی است که Executor ایرفلو مدیریت می‌کند، داخل namespace مشخص شده.\n\n‫توضیح بیشتر:\n‫هر DAG از چند تسک تشکیل شده که توسط Executor اجرا می‌شوند.\n\nاین متریک تعداد تسک‌هایی را نشان می‌دهد‫ که هم‌اکنون روی Executor در حال اجرا هستند.\n\n‫عدد بزرگ یعنی Executor مشغول اجرای تسک‌های زیادی است؛ عدد کوچک یعنی بار اجرای تسک‌ها کمتر است.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "airflow_executor_running_tasks{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of queued tasks on executor",
   "type": "timeseries",
   "description": "Number of queued tasks on executor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "airflow_executor_queued_tasks{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Free slots on executor",
   "type": "timeseries",
   "description": "این متریک  شان‌دهنده‌ی تعداد اسلات‌های‫ آزاد (free slots) در اجرای تسک‌ها توسط executor است\n\n\n‫Executor در Airflow مسئول اجرای تسک‌هاست.\n\n‫هر executor ظرفیت محدودی برای اجرای تسک‌ها دارد که به صورت اسلات (slot) مدیریت می‌شود.\n\nاین متریک نشان می‌دهد که در حال حاضر‫ چند اسلات برای اجرای تسک‌های جدید خالی و آماده هستند.\n\n‫اگر این عدد پایین یا صفر باشد، یعنی executor ظرفیت کافی برای اجرای تسک‌های جدید را ندارد و ممکن است تسک‌ها صف شوند.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "airflow_executor_open_slots{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of DAGs",
   "type": "timeseries",
   "description": "‫این متریک نشان‌دهنده‌ی تعداد DAGهایی است که ایرفلو در حافظه (در DAGBag) بارگذاری کرده است \n\n‫DAGBag مجموعه‌ای از DAGهای تعریف‌شده است که Airflow بارگذاری می‌کند تا بتواند آن‌ها را مدیریت و اجرا کند.\n\n‫این متریک به شما می‌گوید چند DAG در حال حاضر لود شده و آماده اجرا هستند.\n\n‫مقدار این متریک معمولاً برابر است با تعداد DAGهای فعال یا تعریف‌شده در آن محیط.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "airflow_dagbag_size{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Seconds taken to scan and import all DAG files once",
   "type": "timeseries",
   "description": "‫کل زمان صرف‌شده برای پردازش (Parse) DAG ها در یک بازه زمانی مشخص\n\n‫وقتی Airflow دک ها را بارگذاری می‌کند، ابتدا فایل‌های DAG (معمولاً فایل‌های Python) را می‌خواند و پردازش می‌کند.\n\n‫این پردازش شامل تفسیر (پارس کردن) کد DAG و تبدیل آن به ساختار قابل اجرا در Airflow است.\n\nاین متریک زمان کل صرف‌شده برای این‫ پردازش را نشان می‌دهد.\n\n‫اگر مقدار این متریک زیاد باشد، یعنی DAGها زمان زیادی برای پردازش می‌برند که ممکن است نشانه‌ای از سنگینی DAGها یا پیچیدگی زیاد آنها باشد.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "timeseries",
   "description": "‫نشان‌دهنده تعداد دفعاتی است که Airflow در هنگام ایمپورت کردن DAGها با خطا مواجه شده است.\n\n‫هنگامی که Scheduler می‌خواهد DAGها را از فایل‌های پایتون در مسیر dags/ لود کند، این فایل‌ها را ایمپورت می‌کند (مثل اجرای import dag_file.py). اگر در این فرآیند ایمپورت، خطایی در کد وجود داشته باشد (مثل سینتکس اشتباه، نام ماژول اشتباه، ارور در فانکشن، یا حتی مشکل در کانفیگ)، آن فایل به‌عنوان import error ثبت‫ می‌شود.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "airflow_dag_processing_processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "airflow_dag_processing_processes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": " Duration to Adopt Orphaned Task Instances (Kubernetes Executor)",
   "type": "timeseries",
   "description": "‫نشان‌دهنده‌ی مدت‌زمانی است که KubernetesExecutor در Airflow صرف می‌کند تا TaskInstanceهای orphan شده (بدون صاحب) را دوباره به‌عهده بگیرد (adopt).\n\n\n‫در سناریوهایی مثل:\n\n‫ری‌استارت شدن Airflow Scheduler\n\n‫crash کردن بعضی از پادها\n\n‫انتقال وظایف در هنگام failover\n\n‫ممکن است taskهایی که در حال اجرا بودند orphan بشن (یعنی task هنوز در حال اجراست، اما ارتباطش با Scheduler قطع شده).\n\n‫در این حالت، KubernetesExecutor باید آن taskها را شناسایی و دوباره کنترل (adopt) کند.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_kubernetes_executor_adopt_task_instances_duration{namespace=\"$namespace\"}",
     "legendFormat": "Quantile:{{quantile}}"
    }
   ]
  },
  {
   "title": "Duration to Clear Non-Launched Queued Tasks (Kubernetes Executor)",
   "type": "timeseries",
   "description": "‫نشان دهنده مدت‌زمانی است که KubernetesExecutor در Airflow صرف می‌کند تا Taskهایی که در صف هستند ولی هنوز اجرا نشده‌اند و قابل اجرا هم نیستند، پاک (Clear) کند.\n\n‫در شرایط خاص، ممکنه taskهایی:\n\n‫در حالت queued باقی بمونند،\n\n‫اما به دلایلی هیچ‌وقت launch نشن (مثلاً resource کافی در کلاستر وجود نداشته، یا خطایی رخ داده).\n\n‫Airflow برای جلوگیری از گیر کردن این taskها، مکانیزمی دارد تا این‌ها را پاکسازی (clear) کند.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_kubernetes_executor_clear_not_launched_queued_tasks_duration{namespace=\"$namespace\"}",
     "legendFormat": "Quantile:{{quantile}}"
    }
   ]
  }
 ]
}